add_newline = true

format = """
$os\
$directory\
$git_branch\
$git_status\
$lua\
$dotnet\
$character"""

[os]
disabled = false
style = "bold blue"

[os.symbols]
Arch = "󰣇 "

[directory]
style = "bold cyan"
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold purple"

[lua]
symbol = " "
style = "bold blue"
format = "via [$symbol($version )]($style)"

[dotnet]
symbol = "󰪮 "
style = "bold green"
format = "via [$symbol($version )]($style)"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
vicmd_symbol = "[➜](bold yellow) "
